config/routes.rb
Rails.application.routes.draw do

  root 'bus_reservations#new'


  resources :bus_reservations
  resources :dashboards, only: :index
  devise_for :users, controllers: { registrations: "registrations"}



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_reservation.rb
class BusReservation < ApplicationRecord
  validates :first_name, :last_name, :hour, :date, presence: true

  def self.to_csv
    CSV.generate do |csv|
      all.each do |reservation|
        csv << reservation.attributes.values_at(*['date', 'name'])
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bus_reservations_controller.rb
class BusReservationsController < ApplicationController
  before_action :set_bus_reservation, only: [:show, :edit, :update, :destroy]

  # GET /bus_reservations
  # GET /bus_reservations.json
  def index
    @bus_reservations = BusReservation.all
  end

  # GET /bus_reservations/1
  # GET /bus_reservations/1.json
  # def show
  # end

  # GET /bus_reservations/new
  def new
    @bus_reservation = BusReservation.new
  end

  # GET /bus_reservations/1/edit
  def edit
  end

  # POST /bus_reservations
  # POST /bus_reservations.json
  def create
    @bus_reservation = BusReservation.new(bus_reservation_params)

    respond_to do |format|
      if @bus_reservation.save
        format.html { redirect_to @bus_reservation, notice: 'Bus reservation was successfully created.' }
        format.json { render :show, status: :created, location: @bus_reservation }
      else
        format.html { render :new }
        format.json { render json: @bus_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_reservations/1
  # PATCH/PUT /bus_reservations/1.json
  def update
    respond_to do |format|
      if @bus_reservation.update(bus_reservation_params)
        format.html { redirect_to @bus_reservation, notice: 'Bus reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_reservation }
      else
        format.html { render :edit }
        format.json { render json: @bus_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_reservations/1
  # DELETE /bus_reservations/1.json
  # def destroy
  #   @bus_reservation.destroy
  #   respond_to do |format|
  #     format.html { redirect_to bus_reservations_url, notice: 'Bus reservation was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_reservation
      @bus_reservation = BusReservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_reservation_params
      params.require(:bus_reservation).permit(:date, :hour, :first_name, :last_name, :start_location, :end_location, :department)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :authenticate_user!
  def index
    @bus_reservations = BusReservation.all

    respond_to do |format|
      format.html
      format.csv { send_data @bus_reservations.to_csv }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_reservations_helper.rb
module BusReservationsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/bus_reservations/_form.html.erb
<%= simple_form_for(@bus_reservation) do |f| %>

  <%= f.input :date, html5: true %>
  <%= f.input :hour %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/bus_reservations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Editing Bus Reservation</h1>

      <%= render 'form', bus_reservation: @bus_reservation %>

      <%= link_to 'Back', bus_reservations_path %>
    </div>
  </div>
</div>

app/views/bus_reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bus Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bus_reservations.each do |bus_reservation| %>
      <tr>
        <td><%= bus_reservation.first_name %></td>
        <!-- <td><%= link_to 'Edit', edit_bus_reservation_path(bus_reservation) %></td> -->
        <!-- <td><%= link_to 'Destroy', bus_reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus Reservation', new_bus_reservation_path %>

app/views/bus_reservations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <h1>New Bus Reservation</h1>
      <%= render 'form', bus_reservation: @bus_reservation %>
    </div>
  </div>
</div>

app/views/bus_reservations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p id="notice"><%= notice %></p>

      <div class="bus-reservation">
        <ul>
          <li>
            <%= @bus_reservation.first_name %>
          </li>
          <li>
            <%= @bus_reservation.last_name %>
          </li>
          <li>
            <%= @bus_reservation.date %>
          </li>
          <li>
            <%= @bus_reservation.hour %>
          </li>
        </ul>
      </div>

      <%= link_to 'Edit', edit_bus_reservation_path(@bus_reservation), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', bus_reservation_path(@bus_reservation), method: :delete, class: 'btn btn-danger' %>
      <%= link_to 'Back', bus_reservations_path %>
    </div>
  </div>
</div>

app/views/dashboards/index.erb
<%= link_to 'Logout', destroy_user_session_path, class: 'btn', method: :delete %>
<%= link_to 'Edit account', edit_user_registration_path, class: 'btn' %>

<% @bus_reservations.each do |reservation| %>
  <div class="">
    <%= reservation.name %>
    <%= reservation.date %>
  </div>
<% end %>

<%= link_to 'Export as CSV', dashboards_path(format: :csv) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JbApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>